---
- name: This sets up an httpd webserver
  hosts: webservers
  tasks:
  - name: Install the httpd rpm
    yum: name=httpd
  - name: start the httpd service
    service: name=httpd state=started
  - name: Open port 80
    firewalld: service=http permanent=true state=enabled
  - name: start the firewalld service
    service: name=firewalld state=restarted

  - name: Install common software requirements
    yum: pkg={{ item }} state=installed
    with_items:
     - git
     - ntp
     - vim
     
  - name: Creating a file
    file: path=/opt/verizon.txt state=touch
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "6"
